### ISSUE TITLE
Instagram Feed using Javascript isn't delivering content

### ISSUE THREAD

**Issue by SchluribumbiVonDerZukunft** [nitsan-technologies/ns_instagram#17]
I saw on my websites and on https://demo.t3terminal.com/t3t-extensions/instagram that the Instagram Feed using Javascript isn't delivering content. A Customer of mine told me, this issue is since a few weeks.

**Comment by nitsan-technologies** [comment]
Hello @SchluribumbiVonDerZukunft 

Thanks for pointing out the problem. We have checked and noticed that Instagram has introduced **strict-origin-when-cross-origin** policy. So they don't allow cross-site content access anymore. 

Please find the following references that mentioned the same issue.

1. 
![instagram_error_](https://user-images.githubusercontent.com/2622317/111611271-455d8100-8802-11eb-9bef-18e7a2ad796e.png)

2. https://stackoverflow.com/questions/66336314/new-cors-policy-for-instagram-public-api
3. https://github.com/iamcal/oembed/issues/339

For now, we are not sure how to solve this issue. We will check and try to resolve this and notify you here.

Have a great time ahead.

Thanks!
Team NITSAN

**Comment by nitsan-technologies** [comment]
Hi @SchluribumbiVonDerZukunft 

We have released a new version, and in that new version, we have fixed this issue, So will you please check and let us know if you want more support and any queries on this.

Thank you!

**Comment by SchluribumbiVonDerZukunft** [comment]
Thanks a lot for fixing this issue. Now, It works in the installation of my customer :)

**Comment by agenturanmut** [comment]
Hi @nitsan-technologies,

we updated the extension to version 2.2.2 and it is still not loading the images: https://www.preventgroup.com/instagram-test/

Are we doing something wrong?

Kind regards!

**Comment by awidschwendter** [comment]
Hi @nitsan-technologies, is it still working? (only js version) It's not working for me, and your demo frontend also doesn't seem to work.... 
Thx for a short confirmation, 
Best regards!

**Comment by nitsan-technologies** [comment]
Hello @awidschwendter 
Greetings of the day!

Thanks for the message.

FYI, Facebook has deprecated the https://api.instagram.com/oembed/ endpoint on Oct 22, 2020, So all post previews aren't visible anymore. It will show 400 Status Code in the console.
So we request you to use the Instagram Basic API Display API to show the Instagram feed. Please find the documentation here: https://docs.t3terminal.com/en/latest/ExtNsInstagram/Configuration/Index.html#configure-global-settings

Please let's know if you need any further support on this from our side.

Thanks!
Team NITSAN
